name: hello-haskell
version: 0.1.0.0
github: "thomas-gale/hello-haskell"
license: MIT
author: "Thomas Gale"
maintainer: "gale.thomasjames@gmail.com"
copyright: "2021 Thomas Gale"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/thomas-gale/hello-haskell#readme>

dependencies:
  - base >= 4.7 && < 5
  - split

library:
  source-dirs:
    - src
    - src/aoc
    - src/aoc2015
    - src/aoc2021

executables:
  hello-haskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hello-haskell
    when:
      - condition: false
        other-modules: Paths_hello_haskell

tests:
  hello-haskell-test:
    main: Spec.hs
    source-dirs: 
      - test
      - test/aoc2015
      - test/aoc2021
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - QuickCheck
      - hello-haskell
